create table if not exists composites (
  composite_num tinyint default null,
  reading text default null
);

create index composite_num on composites(composite_num);

-- The following translations are by Archimandrite Ephrem Lash of blessed memory.

insert into composites values(2, 'The memory of a just man is praised, and the Lord’s blessing is upon his head. Blessed is one who has found wisdom; a mortal who knows understanding. To import her is better than treasures of gold and silver. She is more valuable than precious stones; nothing of value equals her worth. Justice proceeds from her mouth; she bears law and mercy on her tongue. Therefore, my children, listen to me, for I speak weighty things. And blessed is the one who keeps my ways. For my goings out are the goings out of life, and favour is prepared from the Lord. Therefore I exhort you, and utter my voice to the children of humankind. Because I, Wisdom, have prepared counsel, knowledge and understanding. I have called on them. Counsel and sureness are mine; prudence is mine, strength is mine. I love those who are my friends, while those who seek me will find grace. You innocent, then, understand cunning; you untaught, take it to heart. Listen to me, for I will speak weighty things, and I will open right things from my lips. Because my throat will meditate truth; lying lips are abominable before me. All the words of my mouth are with justice, there is nothing crooked in them nor twisted. They are all straight for those who understand, and right for those who find knowledge. For I teach you what is true, that your hope may be in the Lord and that you may be filled with spirit.');
insert into composites values(3, 'A just man if he comes to his end will be at rest. A just man who dies will condemn the ungodly who are alive; for they will see the end of a just man and will not understand what they counselled concerning him. For the Lord will break the ungodly, render them voiceless and cast them headlong, and he will shake them from the foundations and they will be utterly worsted in sorrow, and their memory shall perish. They shall come with fear at the accounting of their sins, and their iniquities will convict them to their face. Then the just will stand with much boldness in the face of those who afflicted him and made his toils of no account. When they see this they will be troubled with great fear and will be amazed at the wonder of his salvation. For they will say as they repent and with anguish they will groan and say: Is this he whom we fools once made a laughing stock and a byword of reproach? We reckoned his life folly and his end dishonour. How has he been numbered among the children of God and his lot with the Saints? Therefore we have erred from the way of truth and the light of righteousness has not shone on us and the sun has not dawned on us. We have been filled with paths of lawlessness and destruction and journeyed through trackless paths, but have not known the way of the Lord.');
insert into composites values(8, 'Thus says the Lord: Comfort, comfort my people, says God. Priests, speak to the heart of Jerusalem. Comfort her, because her humiliation has been completed; for her has sin has been abolished, because she has received from the Lord’s hand double for her sins. A voice of one crying in the wilderness: Prepare the way of the Lord, make straight the paths of our God. Every valley will be filled and every mountain and hill made low; what is crooked will become straight, and the rough ways will be made smooth; and all flesh shall see the salvation of God. Go up onto a high mountain, you who bring good tidings to Sion; lift up your voice with strength, you who bring good tidings to Jerusalem. Lift it up, do not be afraid. I the Lord God, I, the God of Israel, will hearken and will not forsake them; but I will open rivers from the mountains and springs in the middle of plains. I will turn the wilderness into water meadows and the thirsty earth with water courses. Let the heavens rejoice from on high and let the clouds rain justice. Let the earth sprout and blossom with mercy and justice. Announce a voice of gladness to the end of the earth and let this be heard: Say that the Lord has delivered his servant Jacob. And if they thirst through deserts, he will bring water for them from a rock. Rejoice you barren who have never given birth, break out and shout, you who have never known birth pangs, for the children of the deserted are more than those of her who has a husband.');
insert into composites values(9, 'Thus says the Lord Almighty: See, I am sending my Angel, my messenger, before your face, who will prepare your way before you. And the Lord whom you seek will come to his temple. And who will endure the day of his entrance? And who will withstand at his appearing? Because he will enter like fire in a smelting furnace and like the lye of launderers. And he will come to you in judgement; and he will be a swift witness against the wicked and against adulteresses and against those swear falsely in his name and those who do not fear him, says the Lord Almighty. Because I am the Lord your God, and I have not changed and you, children of Jacob, have perverted the laws and not kept them. Therefore turn back to me and I will turn back to you, says the Lord Almighty. And all the nations will call you blessed and you will know that I am the Lord who discern between just and lawless on the day on which I make a peculiar possession of those who love me. Know then and remember the law of Moses my servant, as I gave him commandment on Horeb, to all Israel ordinances and judgements. And see, I will send you Elias the Thesbite, before the great and manifest day of the Lord comes; he will turn again the heart of father to son and of a man to his neighbour, lest when I come I smite the earth grievously, says the Lord Almighty, God the Holy One of Israel.');
